server:
  port: 8081
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  data:
    mongodb:
      database: microproduct
      host: localhost
      port: 27017
